{"content":"    \r\n    <h1 id=\"System_AggregateException\">\r\n      <span class=\"lang-csharp\">AggregateException</span>\r\n        Class\r\n    </h1>\r\n    \r\n    \r\n    <nav id=\"center-doc-outline\" class=\"doc-outline\" ms.cmpgrp=\"intopic toc\" role=\"navigation\" aria-label=\"On page navigation\">\r\n      <h3>In this Article</h3>\r\n    </nav><div class=\"summary\">\r\n    \t<p>Represents one or more errors that occur during application execution.</p>\n\r\n    </div><h2>Syntax</h2>\r\n    \r\n    \t<h3>Declaration</h3>\r\n    \t<pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">[System.Diagnostics.DebuggerDisplay(&quot;Count = {InnerExceptionCount}&quot;)]\npublic class AggregateException : Exception</code></pre>\r\n    \r\n    \r\n    \r\n    <h3>Inheritance Hierarchy</h3>\r\n    <ul class=\"inheritance\">\r\n        <li class=\"l0\">\r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object\" data-linktype=\"relative-path\">Object</a>\r\n          </div>\r\n        </li>\r\n        <li class=\"l1\">\r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">System.Exception</a>\r\n          </div>\r\n        </li>\r\n      <li class=\"l2\">\r\n        <div class=\"xref\">\r\n          <div class=\"lang-csharp\">AggregateException</div>\r\n        </div>\r\n      </li>\r\n    </ul>\r\n    \r\n      <div class=\"referencebox inheritedMembers\">\r\n        <h3>Inherited Members</h3>\r\n        <h4></h4>\r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_Data\" data-linktype=\"relative-path\">Data</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_GetType\" data-linktype=\"relative-path\">GetType()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_HelpLink\" data-linktype=\"relative-path\">HelpLink</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_HResult\" data-linktype=\"relative-path\">HResult</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_InnerException\" data-linktype=\"relative-path\">InnerException</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_Message\" data-linktype=\"relative-path\">Message</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_SerializeObjectState\" data-linktype=\"relative-path\">SerializeObjectState</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_Source\" data-linktype=\"relative-path\">Source</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_StackTrace\" data-linktype=\"relative-path\">StackTrace</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_TargetSite\" data-linktype=\"relative-path\">TargetSite</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_Equals_System_Object_\" data-linktype=\"relative-path\">Equals(Object)</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_Equals_System_Object_System_Object_\" data-linktype=\"relative-path\">Equals(Object,Object)</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_GetHashCode\" data-linktype=\"relative-path\">GetHashCode()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_MemberwiseClone\" data-linktype=\"relative-path\">MemberwiseClone()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_ReferenceEquals_System_Object_System_Object_\" data-linktype=\"relative-path\">ReferenceEquals(Object,Object)</a>\r\n          </div>\r\n          \r\n      </div>\r\n    \r\n    \r\n      <h2>Remarks</h2>\r\n      <p>AggregateException is used to consolidate multiple failures into a single, throwable exception object. It is used extensively in the <a href=\"../Topic/Task%20Parallel%20Library%20(TPL).md\" data-linktype=\"relative-path\">Task Parallel Library (TPL)</a> and <a href=\"../Topic/Parallel%20LINQ%20(PLINQ).md\" data-linktype=\"relative-path\">Parallel LINQ (PLINQ)</a>. For additional information, see the <a href=\"http://go.microsoft.com/fwlink/p/?LinkId=259617\" data-linktype=\"external\">Aggregating Exceptions</a> entry in the .NET Matters blog. For an example, see <a href=\"http://msdn.microsoft.com/en-us/d6c47ec8-9de9-4880-beb3-ff19ae51565d\" data-linktype=\"external\">NIB: How to: Handle Exceptions Thrown by Tasks</a> and <a href=\"../Topic/How%20to:%20Handle%20Exceptions%20in%20a%20PLINQ%20Query.md\" data-linktype=\"relative-path\">How to: Handle Exceptions in a PLINQ Query</a>.</p>\n\r\n    \r\n    \r\n    <h2>Constructors\r\n     summary</h2>\r\n    \r\n    <table class=\"nameValue\">\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException__ctor\" data-linktype=\"self-bookmark\">AggregateException()</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with a system-supplied message that describes the error.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException__ctor_System_Collections_Generic_IEnumerable_System_Exception__\" data-linktype=\"self-bookmark\">AggregateException(IEnumerable&lt;Exception&gt;)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with references to the inner exceptions that are the cause of this exception.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException__ctor_System_Exception___\" data-linktype=\"self-bookmark\">AggregateException(Exception[])</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with references to the inner exceptions that are the cause of this exception.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException__ctor_System_String_\" data-linktype=\"self-bookmark\">AggregateException(String)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with a specified message that describes the error.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException__ctor_System_Runtime_Serialization_SerializationInfo_System_Runtime_Serialization_StreamingContext_\" data-linktype=\"self-bookmark\">AggregateException(SerializationInfo,StreamingContext)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with serialized data.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException__ctor_System_String_System_Collections_Generic_IEnumerable_System_Exception__\" data-linktype=\"self-bookmark\">AggregateException(String,IEnumerable&lt;Exception&gt;)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with a specified error message and references to the inner exceptions that are the cause of this exception.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException__ctor_System_String_System_Exception_\" data-linktype=\"self-bookmark\">AggregateException(String,Exception)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException__ctor_System_String_System_Exception___\" data-linktype=\"self-bookmark\">AggregateException(String,Exception[])</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with a specified error message and references to the inner exceptions that are the cause of this exception.</p>\n\r\n            </td>\r\n        </tr>\r\n    </table>\r\n    <h2>Properties\r\n     summary</h2>\r\n    \r\n    <table class=\"nameValue\">\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException_InnerExceptions\" data-linktype=\"self-bookmark\">InnerExceptions</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Gets a read-only collection of the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> instances that caused the current exception.</p>\n\r\n            </td>\r\n        </tr>\r\n    </table>\r\n    <h2>Methods\r\n     summary</h2>\r\n    \r\n    <table class=\"nameValue\">\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException_Flatten\" data-linktype=\"self-bookmark\">Flatten()</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Flattens an <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> instances into a single, new instance.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException_GetBaseException\" data-linktype=\"self-bookmark\">GetBaseException()</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Returns the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> that is the root cause of this exception.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException_GetObjectData_System_Runtime_Serialization_SerializationInfo_System_Runtime_Serialization_StreamingContext_\" data-linktype=\"self-bookmark\">GetObjectData(SerializationInfo,StreamingContext)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with serialized data.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException_Handle_System_Func_System_Exception_System_Boolean__\" data-linktype=\"self-bookmark\">Handle(Func&lt;Exception,Boolean&gt;)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Invokes a handler on each <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> contained by this <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a>.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_AggregateException_ToString\" data-linktype=\"self-bookmark\">ToString()</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Creates and returns a string representation of the current <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a>.</p>\n\r\n            </td>\r\n        </tr>\r\n    </table>\r\n    <section class=\"memberGroup\">\r\n      <header class=\"header enable-platform-filter\" id=\"constructors\">\r\n        <h2>Constructors\r\n    </h2>\r\n      </header>\r\n    \r\n      <ul class=\"list-clean enable-platform-filter\">\r\n    \r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException__ctor\">\r\n    \r\n            <a id=\"System_AggregateException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">AggregateException()</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with a system-supplied message that describes the error.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public AggregateException ();</code></pre>\r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>This constructor initializes the <a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a> property of the new instance to a system-supplied message that describes the error, such as &quot;DefaultMessageDisplayedByParameterlessCtorWriterMustSupply&quot; This message takes into account the current system culture.  </p>\n<p> The following table shows the initial property values for an instance of <a class=\"xref\" href=\"system.insufficientmemoryexception\" data-linktype=\"relative-path\">InsufficientMemoryException</a>.  </p>\n<table>\n<thead>\n<tr>\n<th>Property</th>\n<th>Value</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a></td>\n<td><code>null</code>.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a></td>\n<td>The localized error message string.</td>\n</tr>\n</tbody>\n</table>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException__ctor_System_Collections_Generic_IEnumerable_System_Exception__\">\r\n    \r\n            <a id=\"System_AggregateException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">AggregateException(IEnumerable&lt;Exception&gt;)</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with references to the inner exceptions that are the cause of this exception.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public AggregateException (System.Collections.Generic.IEnumerable&lt;Exception&gt; innerExceptions);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>innerExceptions</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.collections.generic.ienumerable-1\" data-linktype=\"relative-path\">IEnumerable</a>&lt;<a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>&gt;</div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The exceptions that are the cause of the current exception.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n              <h4>Exceptions</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></div>\r\n                  </div>\r\n                  <p>The <code>innerExceptions</code> argument is null.</p>\n\r\n                </li>\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentexception\" data-linktype=\"relative-path\">ArgumentException</a></div>\r\n                  </div>\r\n                  <p>An element of <code>innerExceptions</code> is null.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n          \r\n    \r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException__ctor_System_Exception___\">\r\n    \r\n            <a id=\"System_AggregateException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">AggregateException(Exception[])</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with references to the inner exceptions that are the cause of this exception.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public AggregateException (Exception[] innerExceptions);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>innerExceptions</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>[]</div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The exceptions that are the cause of the current exception.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n              <h4>Exceptions</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></div>\r\n                  </div>\r\n                  <p>The <code>innerExceptions</code> argument is null.</p>\n\r\n                </li>\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentexception\" data-linktype=\"relative-path\">ArgumentException</a></div>\r\n                  </div>\r\n                  <p>An element of <code>innerExceptions</code> is null.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n          \r\n    \r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException__ctor_System_String_\">\r\n    \r\n            <a id=\"System_AggregateException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">AggregateException(String)</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with a specified message that describes the error.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public AggregateException (string message);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>message</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>The following table shows the initial property values for an instance of <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a>.  </p>\n<table>\n<thead>\n<tr>\n<th>Property</th>\n<th>Value</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a></td>\n<td><code>null</code>.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a></td>\n<td>The error message string specified in <code>message</code>.</td>\n</tr>\n</tbody>\n</table>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException__ctor_System_Runtime_Serialization_SerializationInfo_System_Runtime_Serialization_StreamingContext_\">\r\n    \r\n            <a id=\"System_AggregateException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">AggregateException(SerializationInfo,StreamingContext)</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with serialized data.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">protected AggregateException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>info</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.serializationinfo\" data-linktype=\"relative-path\">SerializationInfo</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The object that holds the serialized object data.</p>\n\r\n                </li>\r\n                <li>\r\n                  <dl>\r\n                  <dt>context</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.streamingcontext\" data-linktype=\"relative-path\">StreamingContext</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The contextual information about the source or destination.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n              <h4>Exceptions</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></div>\r\n                  </div>\r\n                  <p>The <code>info</code> argument is null.</p>\n\r\n                </li>\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.serializationexception\" data-linktype=\"relative-path\">SerializationException</a></div>\r\n                  </div>\r\n                  <p>The exception could not be deserialized correctly.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see <a href=\"../Topic/XML%20and%20SOAP%20Serialization.md\" data-linktype=\"relative-path\">XML and SOAP Serialization</a>.</p>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException__ctor_System_String_System_Collections_Generic_IEnumerable_System_Exception__\">\r\n    \r\n            <a id=\"System_AggregateException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">AggregateException(String,IEnumerable&lt;Exception&gt;)</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with a specified error message and references to the inner exceptions that are the cause of this exception.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public AggregateException (string message, System.Collections.Generic.IEnumerable&lt;Exception&gt; innerExceptions);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>message</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The error message that explains the reason for the exception.</p>\n\r\n                </li>\r\n                <li>\r\n                  <dl>\r\n                  <dt>innerExceptions</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.collections.generic.ienumerable-1\" data-linktype=\"relative-path\">IEnumerable</a>&lt;<a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>&gt;</div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The exceptions that are the cause of the current exception.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n              <h4>Exceptions</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></div>\r\n                  </div>\r\n                  <p>The <code>innerExceptions</code> argument is null.</p>\n\r\n                </li>\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentexception\" data-linktype=\"relative-path\">ArgumentException</a></div>\r\n                  </div>\r\n                  <p>An element of <code>innerExceptions</code> is null.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n          \r\n    \r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException__ctor_System_String_System_Exception_\">\r\n    \r\n            <a id=\"System_AggregateException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">AggregateException(String,Exception)</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public AggregateException (string message, Exception innerException);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>message</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</p>\n\r\n                </li>\r\n                <li>\r\n                  <dl>\r\n                  <dt>innerException</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">System.Exception</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not <code>null</code>, the current exception is raised in a <code>catch</code> block that handles the inner exception.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n              <h4>Exceptions</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></div>\r\n                  </div>\r\n                  <p>The <code>innerException</code> argument is null.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property. The <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property returns the same value that is passed into the constructor, or <code>null</code> if the <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property does not supply the inner exception value to the constructor.  </p>\n<p> The following table shows the initial property values for an instance of <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a>.  </p>\n<table>\n<thead>\n<tr>\n<th>Property</th>\n<th>Value</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a></td>\n<td><code>null</code>.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a></td>\n<td>The error message string specified in <code>message</code>.</td>\n</tr>\n</tbody>\n</table>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException__ctor_System_String_System_Exception___\">\r\n    \r\n            <a id=\"System_AggregateException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">AggregateException(String,Exception[])</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with a specified error message and references to the inner exceptions that are the cause of this exception.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public AggregateException (string message, Exception[] innerExceptions);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>message</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The error message that explains the reason for the exception.</p>\n\r\n                </li>\r\n                <li>\r\n                  <dl>\r\n                  <dt>innerExceptions</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>[]</div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The exceptions that are the cause of the current exception.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n              <h4>Exceptions</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></div>\r\n                  </div>\r\n                  <p>The <code>innerExceptions</code> argument is null.</p>\n\r\n                </li>\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentexception\" data-linktype=\"relative-path\">ArgumentException</a></div>\r\n                  </div>\r\n                  <p>An element of <code>innerExceptions</code> is null.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n          \r\n    \r\n    \r\n    \r\n    \r\n        </li>\r\n      </ul>\r\n    </section><section class=\"memberGroup\">\r\n      <header class=\"header enable-platform-filter\" id=\"properties\">\r\n        <h2>Properties\r\n    </h2>\r\n      </header>\r\n    \r\n      <ul class=\"list-clean enable-platform-filter\">\r\n    \r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException_InnerExceptions\">\r\n    \r\n            <a id=\"System_AggregateException_InnerExceptions_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">InnerExceptions</div>        \r\n          </div>\r\n    \r\n            <p>Gets a read-only collection of the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> instances that caused the current exception.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public System.Collections.ObjectModel.ReadOnlyCollection&lt;Exception&gt; InnerExceptions { get; }</code></pre>\r\n    \r\n    \r\n    \r\n    \r\n              <h4>Property Value</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.collections.objectmodel.readonlycollection-1\" data-linktype=\"relative-path\">ReadOnlyCollection</a>&lt;<a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>&gt;</div>\r\n                  </div>\r\n                  <p>Returns a read-only collection of the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> instances that caused the current exception.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n          \r\n    \r\n    \r\n    \r\n    \r\n        </li>\r\n      </ul>\r\n    </section><section class=\"memberGroup\">\r\n      <header class=\"header enable-platform-filter\" id=\"methods\">\r\n        <h2>Methods\r\n    </h2>\r\n      </header>\r\n    \r\n      <ul class=\"list-clean enable-platform-filter\">\r\n    \r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException_Flatten\">\r\n    \r\n            <a id=\"System_AggregateException_Flatten_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">Flatten()</div>        \r\n          </div>\r\n    \r\n            <p>Flattens an <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> instances into a single, new instance.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public AggregateException Flatten ();</code></pre>\r\n    \r\n    \r\n    \r\n              <h4>Returns</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a></div>\r\n                  </div>\r\n                  <p>A new, flattened <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a>.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>If a task has an attached child task that throws an exception, that exception is wrapped in an <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> exception before it is propagated to the parent task, which wraps that exception in its own <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> exception before it propagates it back to the calling thread. In such cases, the <a class=\"xref\" href=\"system.aggregateexception#System_AggregateException_InnerExceptions_\" data-linktype=\"relative-path\">InnerExceptions</a> property of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> exception that is caught by the <a class=\"xref\" href=\"system.threading.tasks.task#System_Threading_Tasks_Task_Wait_\" data-linktype=\"relative-path\">Wait</a>, &lt;xref:System.Threading.Tasks.Task%601.Wait%2A?displayProperty=fullName&gt;, <a class=\"xref\" href=\"system.threading.tasks.task#System_Threading_Tasks_Task_WaitAny_\" data-linktype=\"relative-path\">WaitAny</a> or <a class=\"xref\" href=\"system.threading.tasks.task#System_Threading_Tasks_Task_WaitAll_\" data-linktype=\"relative-path\">WaitAll</a> method contains one or more <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> instances, not the original exceptions that caused the fault. To avoid having to iterate over nested <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> exceptions, you can use the Flatten method to remove all the nested <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> exceptions, so that the <a class=\"xref\" href=\"system.aggregateexception#System_AggregateException_InnerExceptions_\" data-linktype=\"relative-path\">InnerExceptions</a> property of the returned <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> object contains the original exceptions.  </p>\n<p> This method recursively flattens all instances of  <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> exceptions that are inner exceptions of the current <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> instance . The inner exceptions returned in the new <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> are the union of all the inner exceptions from exception tree rooted at the current <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> instance.</p>\n\r\n    \r\n            <h4>Example</h4>\r\n            <p>In the following example, nested <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> instances are flattened and handled in just one loop.  </p>\n<pre><code class=\"lang-cs\" name=\"TPL_Exceptions#22\">using System;\nusing System.Threading.Tasks;\n\npublic class Example\n{\n   public static void Main()\n   {\n      var task1 = Task.Factory.StartNew(() =&gt; {\n                     var child1 = Task.Factory.StartNew(() =&gt; {\n                        var child2 = Task.Factory.StartNew(() =&gt; {\n                            // This exception is nested inside three AggregateExceptions.\n                            throw new CustomException(&quot;Attached child2 faulted.&quot;);\n                        }, TaskCreationOptions.AttachedToParent);\n\n                        // This exception is nested inside two AggregateExceptions.\n                        throw new CustomException(&quot;Attached child1 faulted.&quot;);\n                     }, TaskCreationOptions.AttachedToParent);\n      });\n\n      try {\n         task1.Wait();\n      }\n      catch (AggregateException ae) {\n         foreach (var e in ae.Flatten().InnerExceptions) {\n            if (e is CustomException) {\n               Console.WriteLine(e.Message);\n            }\n            else {\n               throw;\n            }\n         }\n      }\n   }\n}\n\npublic class CustomException : Exception\n{\n   public CustomException(String message) : base(message)\n   {}\n}\n// The example displays the following output:\n//    Attached child1 faulted.\n//    Attached child2 faulted.\n</code></pre><pre><code class=\"lang-vb\" name=\"TPL_Exceptions#22\">Imports System.Threading.Tasks\n\nModule Example\n   Public Sub Main()\n      Dim task1 = Task.Factory.StartNew(Sub()\n                                           Dim child1 = Task.Factory.StartNew(Sub()\n                                                                                 Dim child2 = Task.Factory.StartNew(Sub()\n                                                                                                                       Throw New CustomException(&quot;Attached child2 faulted.&quot;)\n                                                                                                                    End Sub,\n                                                                                                                    TaskCreationOptions.AttachedToParent)\n                                                                                                                    Throw New CustomException(&quot;Attached child1 faulted.&quot;)\n                                                                              End Sub,\n                                                                              TaskCreationOptions.AttachedToParent)\n                                        End Sub)\n\n      Try\n         task1.Wait()\n      Catch ae As AggregateException\n         For Each ex In ae.Flatten().InnerExceptions\n            If TypeOf ex Is CustomException Then\n               Console.WriteLine(ex.Message)\n            Else\n               Throw\n            End If\n         Next\n      End Try\n   End Sub\nEnd Module\n\nClass CustomException : Inherits Exception\n   Public Sub New(s As String)\n      MyBase.New(s)\n   End Sub\nEnd Class\n&#39; The example displays the following output:\n&#39;       Attached child1 faulted.\n&#39;       Attached child2 faulted.\n</code></pre><p> You can also use the Flatten method to rethrow the inner exceptions from multiple <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> instances thrown by multiple tasks in a single <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> instance, as the following example shows.  </p>\n<pre><code class=\"lang-cs\" name=\"TPL_Exceptions#13\">using System;\nusing System.Collections.Generic;\nusing System.IO;\nusing System.Threading.Tasks;\npublic class Example\n{\n   public static void Main()\n   {\n       try {\n          ExecuteTasks();\n       }\n       catch (AggregateException ae) {\n          foreach (var e in ae.InnerExceptions)\n             Console.WriteLine(&quot;{0}:<br>   {1}&quot;, e.GetType().Name, e.Message);\n\n       }\n   }\n\n   static void ExecuteTasks()\n   {\n        // Assume this is a user-entered String.\n        String path = @&quot;C:\\&quot;;\n        List&lt;Task&gt; tasks = new List&lt;Task&gt;();\n\n        tasks.Add(Task.Run(() =&gt; {\n                             // This should throw an UnauthorizedAccessEXception.\n                              return Directory.GetFiles(path, &quot;*.txt&quot;,\n                                                        SearchOption.AllDirectories);\n                           } ));\n\n        tasks.Add(Task.Run(() =&gt; {\n                              if (path == @&quot;C:\\&quot;)\n                                 throw new ArgumentException(&quot;The system root is not a valid path.&quot;);\n                              return new String[] { &quot;.txt&quot;, &quot;.dll&quot;, &quot;.exe&quot;, &quot;.bin&quot;, &quot;.dat&quot; };\n                           } ));\n\n        tasks.Add(Task.Run( () =&gt; {\n                               throw new NotImplementedException(&quot;This operation has not been implemented.&quot;);\n                           } ));\n\n        try {\n            Task.WaitAll(tasks.ToArray());\n        }\n        catch (AggregateException ae) {\n            throw ae.Flatten();\n        }\n    }\n}\n// The example displays the following output:\n//       UnauthorizedAccessException:\n//          Access to the path &#39;C:\\Documents and Settings&#39; is denied.\n//       ArgumentException:\n//          The system root is not a valid path.\n//       NotImplementedException:\n//          This operation has not been implemented.\n</code></pre><pre><code class=\"lang-vb\" name=\"TPL_Exceptions#13\">Imports System.Collections.Generic\nImports System.IO\nImports System.Threading.Tasks\n\nModule Example\n    Public Sub Main()\n       Try\n          ExecuteTasks()\n       Catch ae As AggregateException\n          For Each e In ae.InnerExceptions\n             Console.WriteLine(&quot;{0}:{2}   {1}&quot;, e.GetType().Name, e.Message,\n                               vbCrLf)\n          Next\n       End Try\n    End Sub\n\n    Sub ExecuteTasks()\n        &#39; Assume this is a user-entered String.\n        Dim path = &quot;C:\\&quot;\n        Dim tasks As New List(Of Task)\n        \n        tasks.Add(Task.Run(Function()\n                             &#39; This should throw an UnauthorizedAccessEXception.\n                              Return Directory.GetFiles(path, &quot;*.txt&quot;,\n                                                        SearchOption.AllDirectories)\n                           End Function))\n\n        tasks.Add(Task.Run(Function()\n                              If path = &quot;C:\\&quot; Then\n                                 Throw New ArgumentException(&quot;The system root is not a valid path.&quot;)\n                              End If\n                              Return { &quot;.txt&quot;, &quot;.dll&quot;, &quot;.exe&quot;, &quot;.bin&quot;, &quot;.dat&quot; }\n                           End Function))\n\n        tasks.Add(Task.Run(Sub()\n                              Throw New NotImplementedException(&quot;This operation has not been implemented.&quot;)\n                           End Sub))\n\n        Try\n            Task.WaitAll(tasks.ToArray)\n        Catch ae As AggregateException\n            Throw ae.Flatten()\n        End Try\n    End Sub\nEnd Module\n&#39; The example displays the following output:\n&#39;       UnauthorizedAccessException:\n&#39;          Access to the path &#39;C:\\Documents and Settings&#39; is denied.\n&#39;       ArgumentException:\n&#39;          The system root is not a valid path.\n&#39;       NotImplementedException:\n&#39;          This operation has not been implemented.\n</code></pre>\r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException_GetBaseException\">\r\n    \r\n            <a id=\"System_AggregateException_GetBaseException_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">GetBaseException()</div>        \r\n          </div>\r\n    \r\n            <p>Returns the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> that is the root cause of this exception.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public override Exception GetBaseException ();</code></pre>\r\n    \r\n    \r\n    \r\n              <h4>Returns</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">System.Exception</a></div>\r\n                  </div>\r\n                  <p>Returns the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> that is the root cause of this exception.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n          \r\n    \r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException_GetObjectData_System_Runtime_Serialization_SerializationInfo_System_Runtime_Serialization_StreamingContext_\">\r\n    \r\n            <a id=\"System_AggregateException_GetObjectData_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">GetObjectData(SerializationInfo,StreamingContext)</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> class with serialized data.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>info</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.serializationinfo\" data-linktype=\"relative-path\">SerializationInfo</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The object that holds the serialized object data.</p>\n\r\n                </li>\r\n                <li>\r\n                  <dl>\r\n                  <dt>context</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.streamingcontext\" data-linktype=\"relative-path\">StreamingContext</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The contextual information about the source or destination.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n              <h4>Exceptions</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></div>\r\n                  </div>\r\n                  <p>The <code>info</code> argument is null.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see <a href=\"../Topic/XML%20and%20SOAP%20Serialization.md\" data-linktype=\"relative-path\">XML and SOAP Serialization</a>.</p>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException_Handle_System_Func_System_Exception_System_Boolean__\">\r\n    \r\n            <a id=\"System_AggregateException_Handle_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">Handle(Func&lt;Exception,Boolean&gt;)</div>        \r\n          </div>\r\n    \r\n            <p>Invokes a handler on each <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> contained by this <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a>.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public void Handle (Func&lt;Exception,bool&gt; predicate);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>predicate</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.func-2\" data-linktype=\"relative-path\">Func</a>&lt;<a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>,<a class=\"xref\" href=\"system.boolean\" data-linktype=\"relative-path\">Boolean</a>&gt;</div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The predicate to execute for each exception. The predicate accepts as an argument the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> to be processed and returns a Boolean to indicate whether the exception was handled.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n              <h4>Exceptions</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></div>\r\n                  </div>\r\n                  <p>The <code>predicate</code> argument is null.</p>\n\r\n                </li>\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a></div>\r\n                  </div>\r\n                  <p>An exception contained by this <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> was not handled.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>Each invocation of the <code>predicate</code> returns true or false to indicate whether the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> was handled. After all invocations, if any exceptions went unhandled, all unhandled exceptions will be put into a new <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> which will be thrown. Otherwise, the Handle method simply returns. If any invocations of the <code>predicate</code> throws an exception, it will halt the processing of any more exceptions and immediately propagate the thrown exception as-is.</p>\n\r\n    \r\n            <h4>Example</h4>\r\n            <p>Ordinarily, an exception handler that catches an <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> exception uses a <code>foreach</code> loop (in C#) or <code>For Each</code> loop (in Visual Basic) to handle each exception in its <a class=\"xref\" href=\"system.aggregateexception#System_AggregateException_InnerExceptions_\" data-linktype=\"relative-path\">InnerExceptions</a> collection. Instead, the following example uses the Handle method to handle each exception, and only re-throws exceptions that are not <code>CustomException</code> instances.  </p>\n<pre><code class=\"lang-cs\" name=\"TPL_Exceptions#16\">using System;\nusing System.Threading.Tasks;\n\npublic class Example\n{\n   public static void Main()\n   {\n      var task1 = Task.Run( () =&gt; { throw new CustomException(&quot;This exception is expected!&quot;); } );\n\n      try {\n          task1.Wait();\n      }\n      catch (AggregateException ae)\n      {\n         // Call the Handle method to handle the custom exception,\n         // otherwise rethrow the exception.\n         ae.Handle(ex =&gt; { if (ex is CustomException)\n                             Console.WriteLine(ex.Message);\n                          return ex is CustomException;\n                        });\n      }\n   }\n}\n\npublic class CustomException : Exception\n{\n   public CustomException(String message) : base(message)\n   {}\n}\n// The example displays the following output:\n//        This exception is expected!\n</code></pre><pre><code class=\"lang-vb\" name=\"TPL_Exceptions#16\">Imports System.Threading.Tasks\n\nModule Example\n   Public Sub Main()\n      Dim task1 = Task.Run(Sub() Throw New CustomException(&quot;This exception is expected!&quot;))\n\n      Try\n         task1.Wait()\n      Catch ae As AggregateException\n         &#39; Call the Handle method to handle the custom exception,\n         &#39; otherwise rethrow the exception.\n         ae.Handle(Function(e)\n                      If TypeOf e Is CustomException Then\n                         Console.WriteLine(e.Message)\n                      End If\n                      Return TypeOf e Is CustomException\n                   End Function)\n      End Try\n   End Sub\nEnd Module\n\nClass CustomException : Inherits Exception\n   Public Sub New(s As String)\n      MyBase.New(s)\n   End Sub\nEnd Class\n&#39; The example displays the following output:\n&#39;       This exception is expected!\n</code></pre><p> The following is a more complete example that uses the Handle method to provide special handling for an <a class=\"xref\" href=\"system.unauthorizedaccessexception\" data-linktype=\"relative-path\">UnauthorizedAccessException</a> when enumerating files.  </p>\n<pre><code class=\"lang-cs\" name=\"TPL_Exceptions#12\">using System;\nusing System.IO;\nusing System.Threading.Tasks;\n\npublic class Example\n{\n    public static void Main()\n    {\n        // This should throw an UnauthorizedAccessException.\n       try {\n           var files = GetAllFiles(@&quot;C:\\&quot;);\n           if (files != null)\n              foreach (var file in files)\n                 Console.WriteLine(file);\n        }\n        catch (AggregateException ae) {\n           foreach (var ex in ae.InnerExceptions)\n               Console.WriteLine(&quot;{0}: {1}&quot;, ex.GetType().Name, ex.Message);\n        }\n        Console.WriteLine();\n\n        // This should throw an ArgumentException.\n        try {\n           foreach (var s in GetAllFiles(&quot;&quot;))\n              Console.WriteLine(s);\n        }\n        catch (AggregateException ae) {\n           foreach (var ex in ae.InnerExceptions)\n               Console.WriteLine(&quot;{0}: {1}&quot;, ex.GetType().Name, ex.Message);\n        }\n    }\n\n    static string[] GetAllFiles(string path)\n    {\n       var task1 = Task.Run( () =&gt; Directory.GetFiles(path, &quot;*.txt&quot;,\n                                                      SearchOption.AllDirectories));\n\n       try {\n          return task1.Result;\n       }\n       catch (AggregateException ae) {\n          ae.Handle( x =&gt; { // Handle an UnauthorizedAccessException\n                            if (x is UnauthorizedAccessException) {\n                                Console.WriteLine(&quot;You do not have permission to access all folders in this path.&quot;);\n                                Console.WriteLine(&quot;See your network administrator or try another path.&quot;);\n                            }\n                            return x is UnauthorizedAccessException;\n                          });\n          return Array.Empty&lt;String&gt;();\n       }\n   }\n}\n// The example displays the following output:\n//       You do not have permission to access all folders in this path.\n//       See your network administrator or try another path.\n//\n//       ArgumentException: The path is not of a legal form.\n</code></pre><pre><code class=\"lang-vb\" name=\"TPL_Exceptions#12\">Imports System.IO\nImports System.Threading.Tasks\n\nModule Example\n    Public Sub Main()\n        &#39; This should throw an UnauthorizedAccessException.\n       Try\n           Dim files = GetAllFiles(&quot;C:\\&quot;)\n           If files IsNot Nothing Then\n              For Each file In files\n                 Console.WriteLine(file)\n              Next\n           End If\n        Catch ae As AggregateException\n           For Each ex In ae.InnerExceptions\n               Console.WriteLine(&quot;{0}: {1}&quot;, ex.GetType().Name, ex.Message)\n           Next\n        End Try\n        Console.WriteLine()\n\n       &#39; This should throw an ArgumentException.\n        Try\n           For Each s In GetAllFiles(&quot;&quot;)\n              Console.WriteLine(s)\n           Next\n        Catch ae As AggregateException\n           For Each ex In ae.InnerExceptions\n               Console.WriteLine(&quot;{0}: {1}&quot;, ex.GetType().Name, ex.Message)\n           Next\n        End Try\n        Console.WriteLine()\n    End Sub\n\n    Function GetAllFiles(ByVal path As String) As String()\n       Dim task1 = Task.Run( Function()\n                                Return Directory.GetFiles(path, &quot;*.txt&quot;,\n                                                          SearchOption.AllDirectories)\n                             End Function)\n       Try\n          Return task1.Result\n       Catch ae As AggregateException\n          ae.Handle( Function(x)\n                        &#39; Handle an UnauthorizedAccessException\n                        If TypeOf x Is UnauthorizedAccessException Then\n                            Console.WriteLine(&quot;You do not have permission to access all folders in this path.&quot;)\n                            Console.WriteLine(&quot;See your network administrator or try another path.&quot;)\n                        End If\n                        Return TypeOf x Is UnauthorizedAccessException\n                     End Function)\n       End Try\n       Return Array.Empty(Of String)()\n    End Function\nEnd Module\n&#39; The example displays the following output:\n&#39;       You do not have permission to access all folders in this path.\n&#39;       See your network administrator or try another path.\n&#39;\n&#39;       ArgumentException: The path is not of a legal form.\n</code></pre>\r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_AggregateException_ToString\">\r\n    \r\n            <a id=\"System_AggregateException_ToString_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">ToString()</div>        \r\n          </div>\r\n    \r\n            <p>Creates and returns a string representation of the current <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a>.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public override string ToString ();</code></pre>\r\n    \r\n    \r\n    \r\n              <h4>Returns</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></div>\r\n                  </div>\r\n                  <p>A string representation of the current exception.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n          \r\n    \r\n    \r\n    \r\n    \r\n        </li>\r\n      </ul>\r\n    </section>\r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n","outputRootRelativePath":"./","pageMetadata":"<meta name=\"breadcrumb_path\" content=\"breadcrumb/toc.json\">\r\n<meta name=\"search.ms_sitename\" content=\"Docs\">\r\n<meta name=\"search.ms_docsetname\" content=\"fulldocset\">\r\n<meta name=\"locale\" content=\"en-us\">\r\n<meta name=\"site_name\" content=\"Docs\">\r\n<meta name=\"search.ms_product\" content=\"MSDN\">\r\n<meta name=\"depot_name\" content=\"MSDN.fulldocset\">\r\n<meta name=\"ref_skeleton_gitcommit\" content=\"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/501959ac03e19ac52a27aa4c6bbeb980f8b11c8c/fulldocset/System.AggregateException.yml\">\r\n<meta name=\"original_ref_skeleton_git_url\" content=\"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/System.AggregateException.yml\">\r\n<meta name=\"APIName\" content=\"System.AggregateException\">\r\n<meta name=\"APIName\" content=\"System.AggregateException..ctor\">\r\n<meta name=\"APIName\" content=\"System.AggregateException.Flatten\">\r\n<meta name=\"APIName\" content=\"System.AggregateException.GetBaseException\">\r\n<meta name=\"APIName\" content=\"System.AggregateException.GetObjectData\">\r\n<meta name=\"APIName\" content=\"System.AggregateException.Handle\">\r\n<meta name=\"APIName\" content=\"System.AggregateException.InnerExceptions\">\r\n<meta name=\"APIName\" content=\"System.AggregateException.ToString\">\r\n<meta name=\"APILocation\" content=\"mscorlib.dll\">\r\n<meta name=\"TopicType\" content=\"apiref\">\r\n<meta name=\"APIType\" content=\"Assembly\">\r\n<meta name=\"updated_at\" content=\"2017-03-01 01:37 AM\">\r\n<meta name=\"document_id\" content=\"bc503366-1314-a2c4-347a-859a4b167060\">\r\n<meta name=\"original_ecmaxml_local_path\" content=\"W:\\o2y0\\s\\fulldocset\\xml\\System\\AggregateException.xml\">\r\n<meta name=\"pagetype\" content=\"Reference\">\r\n<meta name=\"description\" content=\"Represents one or more errors that occur during application execution.\n\">\r\n<meta name=\"toc_rel\" content=\"_splitted/System/toc1.json\">\r\n<meta name=\"source_url\" content=\"\">\r\n<meta name=\"ms.assetid\" content=\"System.AggregateException\">\r\n","rawMetadata":{"breadcrumb_path":"breadcrumb/toc.json","search.ms_sitename":"Docs","search.ms_docsetname":"fulldocset","version":null,"_op_canonicalUrlPrefix":"https://ppe.docs.microsoft.com/en-us/fulldotnet/","locale":"en-us","site_name":"Docs","search.ms_product":"MSDN","_op_openToPublicContributors":true,"depot_name":"MSDN.fulldocset","_op_gitRefSkeletonCommitHistory":[{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"use plugin in master","commit_sha":"501959ac03e19ac52a27aa4c6bbeb980f8b11c8c","commit_date":"2017-03-01 09:31:20 +0800"},{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"fix pointer ref","commit_sha":"76befb0e7f7b41839ec719047e5b39a5981298f3","commit_date":"2017-02-28 15:47:23 +0800"},{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"switch from platform to version","commit_sha":"78cdacb5ca782478af490a6b30c3a2cb2b6b873e","commit_date":"2017-02-28 15:09:51 +0800"},{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"update platforms","commit_sha":"39ad5a8919a59afc93a79ac4bd8e07c3b471b37a","commit_date":"2017-02-28 10:38:59 +0800"},{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"checkin yml","commit_sha":"da161b792852497df7140d7768cee2eccd9cb43f","commit_date":"2017-02-28 09:36:15 +0800"}],"ref_skeleton_gitcommit":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/501959ac03e19ac52a27aa4c6bbeb980f8b11c8c/fulldocset/System.AggregateException.yml","original_ref_skeleton_git_url":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/System.AggregateException.yml","open_to_public_contributors":true,"api_name":["System.AggregateException","System.AggregateException..ctor","System.AggregateException.Flatten","System.AggregateException.GetBaseException","System.AggregateException.GetObjectData","System.AggregateException.Handle","System.AggregateException.InnerExceptions","System.AggregateException.ToString"],"api_location":["mscorlib.dll"],"topic_type":["apiref"],"api_type":["Assembly"],"f1_keywords":["System.AggregateException","System::AggregateException","System.AggregateException.#ctor","System::AggregateException::#ctor","System.AggregateException.Flatten","System::AggregateException::Flatten","System.AggregateException.GetBaseException","System::AggregateException::GetBaseException","System.AggregateException.GetObjectData","System::AggregateException::GetObjectData","System.AggregateException.Handle","System::AggregateException::Handle","System.AggregateException.InnerExceptions","System::AggregateException::InnerExceptions","System.AggregateException.ToString","System::AggregateException::ToString"],"dev_langs":["csharp"],"updated_at":"2017-03-01 01:37 AM","document_id":"bc503366-1314-a2c4-347a-859a4b167060","original_ecmaxml_local_path":"W:\\o2y0\\s\\fulldocset\\xml\\System\\AggregateException.xml","content_git_url":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/xml/System/AggregateException.xml","layout":"Reference","_op_layout":"Reference","pagetype":"Reference","title":"AggregateException class | Microsoft Docs","_op_ogTitle":"AggregateException class","description":"Represents one or more errors that occur during application execution.\n","toc_asset_id":"_splitted/System/toc.json","toc_rel":"_splitted/System/toc.json","source_url":"","ms.assetid":"System.AggregateException","canonical_url":"https://ppe.docs.microsoft.com/en-us/mergedepotdynamic/system.aggregateexception","_op_canonicalUrl":"https://ppe.docs.microsoft.com/en-us/mergedepotdynamic/system.aggregateexception","fileRelativePath":"System.AggregateException.html"},"themesRelativePathToOutputRoot":"_themes/"}