{"content":"    \r\n    <h1 id=\"System_Runtime_ExceptionServices_ExceptionDispatchInfo\">\r\n      <span class=\"lang-csharp\">ExceptionDispatchInfo</span>\r\n        Class\r\n    </h1>\r\n    \r\n    \r\n    <nav id=\"center-doc-outline\" class=\"doc-outline\" ms.cmpgrp=\"intopic toc\" role=\"navigation\" aria-label=\"On page navigation\">\r\n      <h3>In this Article</h3>\r\n    </nav><div class=\"summary\">\r\n    \t<p>Represents an exception whose state is captured at a certain point in code.</p>\n\r\n    </div><h2>Syntax</h2>\r\n    \r\n    \t<h3>Declaration</h3>\r\n    \t<pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public sealed class ExceptionDispatchInfo</code></pre>\r\n    \r\n    \r\n    \r\n    <h3>Inheritance Hierarchy</h3>\r\n    <ul class=\"inheritance\">\r\n        <li class=\"l0\">\r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object\" data-linktype=\"relative-path\">System.Object</a>\r\n          </div>\r\n        </li>\r\n      <li class=\"l1\">\r\n        <div class=\"xref\">\r\n          <div class=\"lang-csharp\">ExceptionDispatchInfo</div>\r\n        </div>\r\n      </li>\r\n    </ul>\r\n    \r\n      <div class=\"referencebox inheritedMembers\">\r\n        <h3>Inherited Members</h3>\r\n        <h4></h4>\r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_Equals_System_Object_\" data-linktype=\"relative-path\">Equals(Object)</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_Equals_System_Object_System_Object_\" data-linktype=\"relative-path\">Equals(Object,Object)</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_GetHashCode\" data-linktype=\"relative-path\">GetHashCode()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_GetType\" data-linktype=\"relative-path\">GetType()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_MemberwiseClone\" data-linktype=\"relative-path\">MemberwiseClone()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_ReferenceEquals_System_Object_System_Object_\" data-linktype=\"relative-path\">ReferenceEquals(Object,Object)</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_ToString\" data-linktype=\"relative-path\">ToString()</a>\r\n          </div>\r\n          \r\n      </div>\r\n    \r\n    \r\n      <h2>Remarks</h2>\r\n      <p>The ExceptionDispatchInfo object stores the stack trace information and Watson information that the exception contains at the point where it is captured. The exception can be thrown at another time and possibly on another thread by calling the <a class=\"xref\" href=\"system.runtime.exceptionservices.exceptiondispatchinfo#System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw_\" data-linktype=\"relative-path\">Throw</a> method. The exception is thrown as if it had flowed from the point where it was captured to the point where the <a class=\"xref\" href=\"system.runtime.exceptionservices.exceptiondispatchinfo#System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw_\" data-linktype=\"relative-path\">Throw</a> method is called.  </p>\n<p> ExceptionDispatchInfo cannot be serialized and is not intended to cross application domain boundaries.</p>\n\r\n    \r\n    \r\n    <h2>Properties\r\n     summary</h2>\r\n    \r\n    <table class=\"nameValue\">\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_Runtime_ExceptionServices_ExceptionDispatchInfo_SourceException\" data-linktype=\"self-bookmark\">SourceException</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Gets the exception that is represented by the current instance.</p>\n\r\n            </td>\r\n        </tr>\r\n    </table>\r\n    <h2>Methods\r\n     summary</h2>\r\n    \r\n    <table class=\"nameValue\">\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_Runtime_ExceptionServices_ExceptionDispatchInfo_Capture_System_Exception_\" data-linktype=\"self-bookmark\">Capture(Exception)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Creates an <a class=\"xref\" href=\"system.runtime.exceptionservices.exceptiondispatchinfo\" data-linktype=\"relative-path\">ExceptionDispatchInfo</a> object that represents the specified exception at the current point in code.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw\" data-linktype=\"self-bookmark\">Throw()</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Throws the exception that is represented by the current <a class=\"xref\" href=\"system.runtime.exceptionservices.exceptiondispatchinfo\" data-linktype=\"relative-path\">ExceptionDispatchInfo</a> object, after restoring the state that was saved when the exception was captured.</p>\n\r\n            </td>\r\n        </tr>\r\n    </table>\r\n    <section class=\"memberGroup\">\r\n      <header class=\"header enable-platform-filter\" id=\"properties\">\r\n        <h2>Properties\r\n    </h2>\r\n      </header>\r\n    \r\n      <ul class=\"list-clean enable-platform-filter\">\r\n    \r\n        <li class=\" enable-platform-filter\" id=\"System_Runtime_ExceptionServices_ExceptionDispatchInfo_SourceException\">\r\n    \r\n            <a id=\"System_Runtime_ExceptionServices_ExceptionDispatchInfo_SourceException_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">SourceException</div>        \r\n          </div>\r\n    \r\n            <p>Gets the exception that is represented by the current instance.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public Exception SourceException { get; }</code></pre>\r\n    \r\n    \r\n    \r\n    \r\n              <h4>Property Value</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a></div>\r\n                  </div>\r\n                  <p>The exception that is represented by the current instance.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>This property is used by the Task Parallel Library, for example, to combine multiple exceptions in an <a class=\"xref\" href=\"system.aggregateexception\" data-linktype=\"relative-path\">AggregateException</a> object. It is not intended to be used by application code. Use the <a class=\"xref\" href=\"system.runtime.exceptionservices.exceptiondispatchinfo#System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw_\" data-linktype=\"relative-path\">Throw</a> method to restore the state of the captured exception and throw it.</p>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n      </ul>\r\n    </section><section class=\"memberGroup\">\r\n      <header class=\"header enable-platform-filter\" id=\"methods\">\r\n        <h2>Methods\r\n    </h2>\r\n      </header>\r\n    \r\n      <ul class=\"list-clean enable-platform-filter\">\r\n    \r\n        <li class=\" enable-platform-filter\" id=\"System_Runtime_ExceptionServices_ExceptionDispatchInfo_Capture_System_Exception_\">\r\n    \r\n            <a id=\"System_Runtime_ExceptionServices_ExceptionDispatchInfo_Capture_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">Capture(Exception)</div>        \r\n          </div>\r\n    \r\n            <p>Creates an <a class=\"xref\" href=\"system.runtime.exceptionservices.exceptiondispatchinfo\" data-linktype=\"relative-path\">ExceptionDispatchInfo</a> object that represents the specified exception at the current point in code.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public static System.Runtime.ExceptionServices.ExceptionDispatchInfo Capture (Exception source);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>source</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The exception whose state is captured, and which is represented by the returned object.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n              <h4>Returns</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.exceptionservices.exceptiondispatchinfo\" data-linktype=\"relative-path\">ExceptionDispatchInfo</a></div>\r\n                  </div>\r\n                  <p>An object that represents the specified exception at the current point in code.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n              <h4>Exceptions</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <div class=\"single\">                \r\n                      <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentexception\" data-linktype=\"relative-path\">ArgumentException</a></div>\r\n                  </div>\r\n                  <p><code>source</code> is <code>null</code>.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>You can use the <a class=\"xref\" href=\"system.runtime.exceptionservices.exceptiondispatchinfo\" data-linktype=\"relative-path\">ExceptionDispatchInfo</a> object that is returned by this method at another time and possibly on another thread to rethrow the specified exception, as if the exception had flowed from this point where it was captured to the point where it is rethrown.  </p>\n<p> If the exception is active when it is captured, the current stack trace information and Watson information that is contained in the exception is stored.  If it is inactive, that is, if it has not been thrown, it will not have any stack trace information or Watson information.</p>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw\">\r\n    \r\n            <a id=\"System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">Throw()</div>        \r\n          </div>\r\n    \r\n            <p>Throws the exception that is represented by the current <a class=\"xref\" href=\"system.runtime.exceptionservices.exceptiondispatchinfo\" data-linktype=\"relative-path\">ExceptionDispatchInfo</a> object, after restoring the state that was saved when the exception was captured.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public void Throw ();</code></pre>\r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>When the exception is restored, the following string is inserted in the stack trace to indicate the restore point: &quot;End of stack trace from the previous location where the exception was thrown&quot;. This is similar to the way inner exceptions or marshaled exceptions are indicated in stack traces.</p>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n      </ul>\r\n    </section>\r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n","outputRootRelativePath":"./","pageMetadata":"<meta name=\"breadcrumb_path\" content=\"breadcrumb/toc.json\">\r\n<meta name=\"search.ms_sitename\" content=\"Docs\">\r\n<meta name=\"search.ms_docsetname\" content=\"fulldocset\">\r\n<meta name=\"locale\" content=\"en-us\">\r\n<meta name=\"site_name\" content=\"Docs\">\r\n<meta name=\"search.ms_product\" content=\"MSDN\">\r\n<meta name=\"depot_name\" content=\"MSDN.fulldocset\">\r\n<meta name=\"original_ref_skeleton_git_url\" content=\"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/System.Runtime.ExceptionServices.ExceptionDispatchInfo.yml\">\r\n<meta name=\"APIName\" content=\"System.Runtime.ExceptionServices.ExceptionDispatchInfo\">\r\n<meta name=\"APIName\" content=\"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture\">\r\n<meta name=\"APIName\" content=\"System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException\">\r\n<meta name=\"APIName\" content=\"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw\">\r\n<meta name=\"APILocation\" content=\"mscorlib.dll\">\r\n<meta name=\"TopicType\" content=\"apiref\">\r\n<meta name=\"APIType\" content=\"Assembly\">\r\n<meta name=\"updated_at\" content=\"2017-03-10 02:17 AM\">\r\n<meta name=\"document_id\" content=\"c58fcb46-d247-dff0-3728-1d5c6e480aa1\">\r\n<meta name=\"original_ecmaxml_local_path\" content=\"W:\\vejk\\s\\fulldocset\\xml\\System.Runtime.ExceptionServices\\ExceptionDispatchInfo.xml\">\r\n<meta name=\"pagetype\" content=\"Reference\">\r\n<meta name=\"description\" content=\"Represents an exception whose state is captured at a certain point in code.\n\">\r\n<meta name=\"toc_rel\" content=\"_splitted/System.Runtime.ExceptionServices/toc1.json\">\r\n<meta name=\"source_url\" content=\"\">\r\n<meta name=\"ms.assetid\" content=\"System.Runtime.ExceptionServices.ExceptionDispatchInfo\">\r\n","rawMetadata":{"breadcrumb_path":"breadcrumb/toc.json","search.ms_sitename":"Docs","search.ms_docsetname":"fulldocset","version":null,"_op_canonicalUrlPrefix":"https://ppe.docs.microsoft.com/en-us/fulldotnet/","locale":"en-us","site_name":"Docs","search.ms_product":"MSDN","_op_openToPublicContributors":true,"depot_name":"MSDN.fulldocset","_op_gitRefSkeletonCommitHistory":[],"original_ref_skeleton_git_url":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/System.Runtime.ExceptionServices.ExceptionDispatchInfo.yml","open_to_public_contributors":true,"api_name":["System.Runtime.ExceptionServices.ExceptionDispatchInfo","System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture","System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException","System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw"],"api_location":["mscorlib.dll"],"topic_type":["apiref"],"api_type":["Assembly"],"f1_keywords":["System.Runtime.ExceptionServices.ExceptionDispatchInfo","System::Runtime::ExceptionServices::ExceptionDispatchInfo","System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture","System::Runtime::ExceptionServices::ExceptionDispatchInfo::Capture","System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException","System::Runtime::ExceptionServices::ExceptionDispatchInfo::SourceException","System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","System::Runtime::ExceptionServices::ExceptionDispatchInfo::Throw"],"dev_langs":["csharp"],"updated_at":"2017-03-10 02:17 AM","document_id":"c58fcb46-d247-dff0-3728-1d5c6e480aa1","original_ecmaxml_local_path":"W:\\vejk\\s\\fulldocset\\xml\\System.Runtime.ExceptionServices\\ExceptionDispatchInfo.xml","content_git_url":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/xml/System.Runtime.ExceptionServices/ExceptionDispatchInfo.xml","layout":"Reference","_op_layout":"Reference","pagetype":"Reference","title":"ExceptionDispatchInfo class | Microsoft Docs","_op_ogTitle":"ExceptionDispatchInfo class","description":"Represents an exception whose state is captured at a certain point in code.\n","toc_asset_id":"_splitted/System.Runtime.ExceptionServices/toc.json","toc_rel":"_splitted/System.Runtime.ExceptionServices/toc.json","source_url":"","ms.assetid":"System.Runtime.ExceptionServices.ExceptionDispatchInfo","canonical_url":"https://ppe.docs.microsoft.com/en-us/mergedepotdynamic/system.runtime.exceptionservices.exceptiondispatchinfo","_op_canonicalUrl":"https://ppe.docs.microsoft.com/en-us/mergedepotdynamic/system.runtime.exceptionservices.exceptiondispatchinfo","fileRelativePath":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.html"},"themesRelativePathToOutputRoot":"_themes/"}