{"content":"    \r\n    <h1 id=\"System_NullReferenceException\">\r\n      <span class=\"lang-csharp\">NullReferenceException</span>\r\n        Class\r\n    </h1>\r\n    \r\n    \r\n    <nav id=\"center-doc-outline\" class=\"doc-outline\" ms.cmpgrp=\"intopic toc\" role=\"navigation\" aria-label=\"On page navigation\">\r\n      <h3>In this Article</h3>\r\n    </nav><div class=\"summary\">\r\n    \t<p>The exception that is thrown when there is an attempt to dereference a null object reference.</p>\n\r\n    </div><h2>Syntax</h2>\r\n    \r\n    \t<h3>Declaration</h3>\r\n    \t<pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">[System.Runtime.InteropServices.ComVisible(true)]\npublic class NullReferenceException : SystemException</code></pre>\r\n    \r\n    \r\n    \r\n    <h3>Inheritance Hierarchy</h3>\r\n    <ul class=\"inheritance\">\r\n        <li class=\"l0\">\r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object\" data-linktype=\"relative-path\">Object</a>\r\n          </div>\r\n        </li>\r\n        <li class=\"l1\">\r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>\r\n          </div>\r\n        </li>\r\n        <li class=\"l2\">\r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.systemexception\" data-linktype=\"relative-path\">System.SystemException</a>\r\n          </div>\r\n        </li>\r\n      <li class=\"l3\">\r\n        <div class=\"xref\">\r\n          <div class=\"lang-csharp\">NullReferenceException</div>\r\n        </div>\r\n      </li>\r\n    </ul>\r\n    \r\n      <div class=\"referencebox inheritedMembers\">\r\n        <h3>Inherited Members</h3>\r\n        <h4></h4>\r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_Data\" data-linktype=\"relative-path\">Data</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_GetBaseException\" data-linktype=\"relative-path\">GetBaseException()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_GetObjectData_System_Runtime_Serialization_SerializationInfo_System_Runtime_Serialization_StreamingContext_\" data-linktype=\"relative-path\">GetObjectData(SerializationInfo,StreamingContext)</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_GetType\" data-linktype=\"relative-path\">GetType()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_HelpLink\" data-linktype=\"relative-path\">HelpLink</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_HResult\" data-linktype=\"relative-path\">HResult</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_InnerException\" data-linktype=\"relative-path\">InnerException</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_Message\" data-linktype=\"relative-path\">Message</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_SerializeObjectState\" data-linktype=\"relative-path\">SerializeObjectState</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_Source\" data-linktype=\"relative-path\">Source</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_StackTrace\" data-linktype=\"relative-path\">StackTrace</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_TargetSite\" data-linktype=\"relative-path\">TargetSite</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.exception#System_Exception_ToString\" data-linktype=\"relative-path\">ToString()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_Equals_System_Object_\" data-linktype=\"relative-path\">Equals(Object)</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_Equals_System_Object_System_Object_\" data-linktype=\"relative-path\">Equals(Object,Object)</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_GetHashCode\" data-linktype=\"relative-path\">GetHashCode()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_MemberwiseClone\" data-linktype=\"relative-path\">MemberwiseClone()</a>\r\n          </div>\r\n          , \r\n          <div class=\"lang-csharp\">\r\n            <a class=\"xref\" href=\"system.object#System_Object_ReferenceEquals_System_Object_System_Object_\" data-linktype=\"relative-path\">ReferenceEquals(Object,Object)</a>\r\n          </div>\r\n          \r\n      </div>\r\n    \r\n    \r\n      <h2>Remarks</h2>\r\n      <p>A NullReferenceException exception is thrown when you try to access a member on a type whose value is <code>null</code>. A NullReferenceException exception typically reflects developer error and is thrown in the following scenarios:  </p>\n<ul>\n<li><p>You&#39;ve forgotten to instantiate a reference type. In the following example, <code>names</code> is declared but never instantiated:  </p>\n<pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#1\">using System;\nusing System.Collections.Generic;\n\npublic class Example\n{\n   public static void Main(string[] args)\n   {\n      int value = Int32.Parse(args[0]);\n      List&lt;String&gt; names;\n      if (value &gt; 0)\n         names = new List&lt;String&gt;();\n      \n      names.Add(&quot;Major Major Major&quot;);       \n   }\n}\n// Compilation displays a warning like the following:\n//    Example1.vb(10) : warning BC42104: Variable //names// is used before it \n//    has been assigned a value. A null reference exception could result \n//    at runtime.\n//    \n//          names.Add(&quot;Major Major Major&quot;)\n//          ~~~~~\n// The example displays output like the following output:\n//    Unhandled Exception: System.NullReferenceException: Object reference \n//    not set to an instance of an object.\n//       at Example.Main()\n</code></pre><pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#1\">Imports System.Collections.Generic\n\nModule Example\n   Public Sub Main()\n      Dim names As List(Of String)\n      names.Add(&quot;Major Major Major&quot;)       \n   End Sub\nEnd Module\n&#39; Compilation displays a warning like the following:\n&#39;    Example1.vb(10) : warning BC42104: Variable &#39;names&#39; is used before it \n&#39;    has been assigned a value. A null reference exception could result \n&#39;    at runtime.\n&#39;    \n&#39;          names.Add(&quot;Major Major Major&quot;)\n&#39;          ~~~~~\n&#39; The example displays output like the following output:\n&#39;    Unhandled Exception: System.NullReferenceException: Object reference \n&#39;    not set to an instance of an object.\n&#39;       at Example.Main()\n</code></pre><p> Some compilers issue a warning when they compile this code. Others issue an error, and the compilation fails. To address this problem, instantiate the object so that its value is no longer <code>null</code>. The following example does this by calling a type&#39;s class constructor.  </p>\n<pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#2\">using System;\nusing System.Collections.Generic;\n\npublic class Example\n{\n   public static void Main()\n   {\n      List&lt;String&gt; names = new List&lt;String&gt;();\n      names.Add(&quot;Major Major Major&quot;);\n   }\n}\n</code></pre><pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#2\">Imports System.Collections.Generic\n\nModule Example\n   Public Sub Main()\n      Dim names As New List(Of String)()\n      names.Add(&quot;Major Major Major&quot;)       \n   End Sub\nEnd Module\n</code></pre></li>\n<li><p>You&#39;ve forgotten to dimension an array before initializing it. In the following example, <code>values</code> is declared to be an integer array, but the number of elements that it contains is never specified. The attempt to initialize its values therefore thrown a  NullReferenceException exception.  </p>\n<pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#10\">Module Example\n   Public Sub Main()\n       Dim values() As Integer\n       For ctr As Integer = 0 To 9\n          values(ctr) = ctr * 2\n       Next\n          \n       For Each value In values\n          Console.WriteLine(value)\n       Next      \n   End Sub\nEnd Module\n&#39; The example displays the following output:\n&#39;    Unhandled Exception: \n&#39;       System.NullReferenceException: Object reference not set to an instance of an object.\n&#39;       at Example.Main()\n</code></pre><pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#10\">using System;\n\npublic class Example\n{\n   public static void Main()\n   {\n       int[] values = null;\n       for (int ctr = 0; ctr &lt;= 9; ctr++)\n          values[ctr] = ctr * 2;\n          \n       foreach (var value in values)\n          Console.WriteLine(value);   \n   }\n}\n// The example displays the following output:\n//    Unhandled Exception: \n//       System.NullReferenceException: Object reference not set to an instance of an object.\n//       at Example.Main()\n</code></pre><p> You can eliminate the exception by declaring the number of elements in the array before initializing it, as the following example does.  </p>\n<pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#11\">using System;\n\npublic class Example\n{\n   public static void Main()\n   {\n       int[] values = new int[10];\n       for (int ctr = 0; ctr &lt;= 9; ctr++)\n          values[ctr] = ctr * 2;\n          \n       foreach (var value in values)\n          Console.WriteLine(value);   \n   }\n}\n// The example displays the following output:\n//    0\n//    2\n//    4\n//    6\n//    8\n//    10\n//    12\n//    14\n//    16\n//    18\n</code></pre><pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#11\">Module Example\n   Public Sub Main()\n       Dim values(9) As Integer\n       For ctr As Integer = 0 To 9\n          values(ctr) = ctr * 2\n       Next\n          \n       For Each value In values\n          Console.WriteLine(value)\n       Next      \n   End Sub\nEnd Module\n&#39; The example displays the following output:\n&#39;    0\n&#39;    2\n&#39;    4\n&#39;    6\n&#39;    8\n&#39;    10\n&#39;    12\n&#39;    14\n&#39;    16\n&#39;    18\n</code></pre><p> For more information on declaring and initializing arrays, see <a href=\"../Topic/Arrays%20(C%23%20Programming%20Guide).md\" data-linktype=\"relative-path\">Arrays</a> and <a href=\"../Topic/Arrays%20in%20Visual%20Basic.md\" data-linktype=\"relative-path\">Arrays</a>.  </p>\n</li>\n<li><p>You get a <strong>null</strong> return value from a method, and then call a method on the returned type. This sometimes is the result of a documentation error; the documentation fails to note that a method call can return <code>null</code>. In other cases, your code erroneously assumes that the method will always return a non-<strong>null</strong> value.  </p>\n<p> The code in the following example assumes that the &lt;xref:System.Array.Find%2A?displayProperty=fullName&gt; method always returns <code>Person</code> object whose <code>FirstName</code> field matches a search string. Because there is no match, the runtime throws a NullReferenceException exception.  </p>\n<pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#4\">Module Example\n   Public Sub Main()\n      Dim persons() As Person = Person.AddRange( { &quot;Abigail&quot;, &quot;Abra&quot;,\n                                                   &quot;Abraham&quot;, &quot;Adrian&quot;,\n                                                   &quot;Ariella&quot;, &quot;Arnold&quot;, \n                                                   &quot;Aston&quot;, &quot;Astor&quot; } )    \n      Dim nameToFind As String = &quot;Robert&quot;\n      Dim found As Person = Array.Find(persons, Function(p) p.FirstName = nameToFind)\n      Console.WriteLine(found.FirstName)\n   End Sub\nEnd Module\n\nPublic Class Person\n   Public Shared Function AddRange(firstNames() As String) As Person()\n      Dim p(firstNames.Length - 1) As Person\n      For ctr As Integer = 0 To firstNames.Length - 1\n         p(ctr) = New Person(firstNames(ctr))\n      Next   \n      Return p\n   End Function\n   \n   Public Sub New(firstName As String)\n      Me.FirstName = firstName\n   End Sub \n   \n   Public FirstName As String\nEnd Class\n&#39; The example displays the following output:\n&#39;       Unhandled Exception: System.NullReferenceException: \n&#39;       Object reference not set to an instance of an object.\n&#39;          at Example.Main()\n</code></pre><pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#4\">using System;\n\npublic class Example\n{\n   public static void Main()\n   {\n      Person[] persons = Person.AddRange( new String[] { &quot;Abigail&quot;, &quot;Abra&quot;, \n                                          &quot;Abraham&quot;, &quot;Adrian&quot;, &quot;Ariella&quot;, \n                                          &quot;Arnold&quot;, &quot;Aston&quot;, &quot;Astor&quot; } );    \n      String nameToFind = &quot;Robert&quot;;\n      Person found = Array.Find(persons, p =&gt; p.FirstName == nameToFind);\n      Console.WriteLine(found.FirstName);\n   }\n}\n\npublic class Person\n{\n   public static Person[] AddRange(String[] firstNames) \n   {\n      Person[] p = new Person[firstNames.Length];\n      for (int ctr = 0; ctr &lt; firstNames.Length; ctr++)\n         p[ctr] = new Person(firstNames[ctr]);\n\n      return p;\n   }\n   \n   public Person(String firstName)\n   {\n      this.FirstName = firstName;\n   } \n   \n   public String FirstName;\n}\n// The example displays the following output:\n//       Unhandled Exception: System.NullReferenceException: \n//       Object reference not set to an instance of an object.\n//          at Example.Main()\n</code></pre><p> To address this problem, test the method&#39;s return value to ensure that it is not <code>null</code> before calling any of its members, as the following example does.  </p>\n<pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#5\">using System;\n\npublic class Example\n{\n   public static void Main()\n   {\n      Person[] persons = Person.AddRange( new String[] { &quot;Abigail&quot;, &quot;Abra&quot;, \n                                          &quot;Abraham&quot;, &quot;Adrian&quot;, &quot;Ariella&quot;, \n                                          &quot;Arnold&quot;, &quot;Aston&quot;, &quot;Astor&quot; } );    \n      String nameToFind = &quot;Robert&quot;;\n      Person found = Array.Find(persons, p =&gt; p.FirstName == nameToFind);\n      if (found != null)\n         Console.WriteLine(found.FirstName);\n      else\n         Console.WriteLine(&quot;{0} not found.&quot;, nameToFind);   \n   }\n}\n\npublic class Person\n{\n   public static Person[] AddRange(String[] firstNames) \n   {\n      Person[] p = new Person[firstNames.Length];\n      for (int ctr = 0; ctr &lt; firstNames.Length; ctr++)\n         p[ctr] = new Person(firstNames[ctr]);\n\n      return p;\n   }\n   \n   public Person(String firstName)\n   {\n      this.FirstName = firstName;\n   } \n   \n   public String FirstName;\n}\n// The example displays the following output:\n//        Robert not found\n</code></pre><pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#5\">Module Example\n   Public Sub Main()\n      Dim persons() As Person = Person.AddRange( { &quot;Abigail&quot;, &quot;Abra&quot;,\n                                                   &quot;Abraham&quot;, &quot;Adrian&quot;,\n                                                   &quot;Ariella&quot;, &quot;Arnold&quot;, \n                                                   &quot;Aston&quot;, &quot;Astor&quot; } )    \n      Dim nameToFind As String = &quot;Robert&quot;\n      Dim found As Person = Array.Find(persons, Function(p) p.FirstName = nameToFind)\n      If found IsNot Nothing Then\n         Console.WriteLine(found.FirstName)\n      Else\n         Console.WriteLine(&quot;{0} not found.&quot;, nameToFind)\n      End If   \n   End Sub\nEnd Module\n\nPublic Class Person\n   Public Shared Function AddRange(firstNames() As String) As Person()\n      Dim p(firstNames.Length - 1) As Person\n      For ctr As Integer = 0 To firstNames.Length - 1\n         p(ctr) = New Person(firstNames(ctr))\n      Next   \n      Return p\n   End Function\n   \n   Public Sub New(firstName As String)\n      Me.FirstName = firstName\n   End Sub \n   \n   Public FirstName As String\nEnd Class\n&#39; The example displays the following output:\n&#39;       Robert not found\n</code></pre></li>\n<li><p>You&#39;re using an expression (for example, you&#39;re chaining a list of methods or properties together) to retrieve a value and, although you&#39;re checking whether the value is <code>null</code>, the runtime still throws a NullReferenceException exception. This occurs because one of the intermediate values in the expression returns <code>null</code>. As a result, your rest for <code>null</code> is never evaluated.  </p>\n<p> The following example defines a <code>Pages</code> object that  caches information about web pages, which are presented by <code>Page</code> objects. The <code>Example.Main</code> method checks whether the current web page has a non-null title and, if it does, displays the title. Despite this check, however, the method throws a NullReferenceException exception.  </p>\n<pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#6\">using System;\n\npublic class Example\n{\n   public static void Main()\n   {\n      var pages = new Pages();\n      if (! String.IsNullOrEmpty(pages.CurrentPage.Title)) {\n         String title = pages.CurrentPage.Title;\n         Console.WriteLine(&quot;Current title: &#39;{0}&#39;&quot;, title);\n      }\n   }\n}\n\npublic class Pages \n{\n   Page[] page = new Page[10];\n   int ctr = 0;\n   \n   public Page CurrentPage\n   {\n      get { return page[ctr]; }\n      set {\n         // Move all the page objects down to accommodate the new one.\n         if (ctr &gt; page.GetUpperBound(0)) {\n            for (int ndx = 1; ndx &lt;= page.GetUpperBound(0); ndx++)\n               page[ndx - 1] = page[ndx];\n         }    \n         page[ctr] = value;\n         if (ctr &lt; page.GetUpperBound(0))\n            ctr++; \n      }\n   }\n   \n   public Page PreviousPage\n   {\n      get {\n         if (ctr == 0) { \n            if (page[0] == null)\n               return null;\n            else\n               return page[0];\n         }\n         else {\n            ctr--;\n            return page[ctr + 1];\n         }\n      }\n   }         \n}\n\npublic class Page\n{\n   public Uri URL;\n   public String Title;\n}\n// The example displays the following output:\n//    Unhandled Exception: \n//       System.NullReferenceException: Object reference not set to an instance of an object.\n//       at Example.Main()\n</code></pre><pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#6\">Module Example\n   Public Sub Main()\n      Dim pages As New Pages()\n      Dim title As String = pages.CurrentPage.Title\n   End Sub\nEnd Module\n\nPublic Class Pages \n   Dim page(9) As Page\n   Dim ctr As Integer = 0\n   \n   Public Property CurrentPage As Page\n      Get\n         Return page(ctr)\n      End Get\n      Set\n         &#39; Move all the page objects down to accommodate the new one.\n         If ctr &gt; page.GetUpperBound(0) Then\n            For ndx As Integer = 1 To page.GetUpperBound(0)\n               page(ndx - 1) = page(ndx)\n            Next\n         End If    \n         page(ctr) = value\n         If ctr &lt; page.GetUpperBound(0) Then ctr += 1 \n      End Set\n   End Property\n   \n   Public ReadOnly Property PreviousPage As Page\n      Get\n         If ctr = 0 Then \n            If page(0) Is Nothing Then\n               Return Nothing\n            Else\n               Return page(0)\n            End If   \n         Else\n            ctr -= 1\n            Return page(ctr + 1)\n         End If\n      End Get\n   End Property         \nEnd Class\n\nPublic Class Page\n   Public URL As Uri\n   Public Title As String\nEnd Class\n&#39; The example displays the following output:\n&#39;    Unhandled Exception: \n&#39;       System.NullReferenceException: Object reference not set to an instance of an object.\n&#39;       at Example.Main()\n</code></pre><p> The exception is thrown because <code>pages.CurrentPage</code> returns <code>null</code> if no page information is  stored in the cache. This exception can be corrected by testing the value of the <code>CurrentPage</code> property before retrieving the current <code>Page</code> object&#39;s <code>Title</code> property, as the following example does:  </p>\n<pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#7\">Module Example\n   Public Sub Main()\n      Dim pages As New Pages()\n      Dim current As Page = pages.CurrentPage\n      If current IsNot Nothing Then \n         Dim title As String = current.Title\n         Console.WriteLine(&quot;Current title: &#39;{0}&#39;&quot;, title)\n      Else\n         Console.WriteLine(&quot;There is no page information in the cache.&quot;)\n      End If   \n   End Sub\nEnd Module\n&#39; The example displays the following output:\n&#39;       There is no page information in the cache.\n</code></pre><pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#7\">using System;\n\npublic class Example\n{\n   public static void Main()\n   {\n      var pages = new Pages();\n      Page current = pages.CurrentPage;\n      if (current != null) {  \n         String title = current.Title;\n         Console.WriteLine(&quot;Current title: &#39;{0}&#39;&quot;, title);\n      }\n      else {\n         Console.WriteLine(&quot;There is no page information in the cache.&quot;);\n      }   \n   }\n}\n// The example displays the following output:\n//       There is no page information in the cache.\n</code></pre></li>\n<li><p>You&#39;re enumerating the elements of an array that contains reference types, and your attempt to process one of the elements throws a NullReferenceException exception.  </p>\n<p> The following example defines a string array. A <code>for</code> statement enumerates the elements in the array and calls each string&#39;s <a class=\"xref\" href=\"system.string#System_String_Trim_\" data-linktype=\"relative-path\">Trim</a> method before displaying the string.  </p>\n<pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#8\">using System;\n\npublic class Example\n{\n   public static void Main()\n   {\n      String[] values = { &quot;one&quot;, null, &quot;two&quot; };\n      for (int ctr = 0; ctr &lt;= values.GetUpperBound(0); ctr++)\n         Console.Write(&quot;{0}{1}&quot;, values[ctr].Trim(), \n                       ctr == values.GetUpperBound(0) ? &quot;&quot; : &quot;, &quot;); \n      Console.WriteLine();\n   }\n}\n// The example displays the following output:\n//    Unhandled Exception: \n//       System.NullReferenceException: Object reference not set to an instance of an object.\n//       at Example.Main()\n</code></pre><pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#8\">Module Example\n   Public Sub Main()\n      Dim values() As String = { &quot;one&quot;, Nothing, &quot;two&quot; }\n      For ctr As Integer = 0 To values.GetUpperBound(0)\n         Console.Write(&quot;{0}{1}&quot;, values(ctr).Trim(), \n                       If(ctr = values.GetUpperBound(0), &quot;&quot;, &quot;, &quot;)) \n      Next\n      Console.WriteLine()\n   End Sub\nEnd Module\n&#39; The example displays the following output:\n&#39;    Unhandled Exception: System.NullReferenceException: \n&#39;       Object reference not set to an instance of an object.\n&#39;       at Example.Main()\n</code></pre><p> This exception occurs if you assume that each element of the array must contain a non-null value, and the value of the array element is in fact <code>null</code>. The exception can be eliminated by testing whether the element is <code>null</code> before performing any operation on that element, as the following example shows.  </p>\n<pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#9\">using System;\n\npublic class Example\n{\n   public static void Main()\n   {\n      String[] values = { &quot;one&quot;, null, &quot;two&quot; };\n      for (int ctr = 0; ctr &lt;= values.GetUpperBound(0); ctr++)\n         Console.Write(&quot;{0}{1}&quot;, \n                       values[ctr] != null ? values[ctr].Trim() : &quot;&quot;, \n                       ctr == values.GetUpperBound(0) ? &quot;&quot; : &quot;, &quot;); \n      Console.WriteLine();\n   }\n}\n// The example displays the following output:\n//       one, , two\n</code></pre><pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#9\">Module Example\n   Public Sub Main()\n      Dim values() As String = { &quot;one&quot;, Nothing, &quot;two&quot; }\n      For ctr As Integer = 0 To values.GetUpperBound(0)\n         Console.Write(&quot;{0}{1}&quot;, \n                       If(values(ctr) IsNot Nothing, values(ctr).Trim(), &quot;&quot;), \n                       If(ctr = values.GetUpperBound(0), &quot;&quot;, &quot;, &quot;)) \n      Next\n      Console.WriteLine()\n   End Sub\nEnd Module\n&#39; The example displays the following output:\n&#39;       one, , two\n</code></pre></li>\n<li><p>A NullReferenceException exception is thrown by a method that is passed <code>null</code>. Some methods validate the arguments that are passed to them. If they do and one of the arguments is <code>null</code>, the method throws an <a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">System.ArgumentNullException</a> exception. Otherwise, it throws a NullReferenceException exception. The following example illustrates this scenario.  </p>\n<pre><code class=\"lang-vb\" name=\"System.NullReferenceException.Class#3\">Imports System.Collections.Generic\n\nModule Example\n   Public Sub Main()\n      Dim names As List(Of String) = GetData()\n      PopulateNames(names)\n   End Sub\n   \n   Private Sub PopulateNames(names As List(Of String))\n      Dim arrNames() As String = { &quot;Dakota&quot;, &quot;Samuel&quot;, &quot;Nikita&quot;,\n                                   &quot;Koani&quot;, &quot;Saya&quot;, &quot;Yiska&quot;, &quot;Yumaevsky&quot; }\n      For Each arrName In arrNames\n         names.Add(arrName)\n      Next\n   End Sub\n   \n   Private Function GetData() As List(Of String)\n      Return Nothing   \n   End Function\nEnd Module\n&#39; The example displays output like the following:\n&#39;    Unhandled Exception: System.NullReferenceException: Object reference \n&#39;    not set to an instance of an object.\n&#39;       at Example.PopulateNames(List`1 names)\n&#39;       at Example.Main()\n</code></pre><pre><code class=\"lang-cs\" name=\"System.NullReferenceException.Class#3\">using System;\nusing System.Collections.Generic;\n\npublic class Example\n{\n   public static void Main()\n   {\n      List&lt;String&gt; names = GetData();\n      PopulateNames(names);\n   }\n\n   private static void PopulateNames(List&lt;String&gt; names)\n   {\n      String[] arrNames = { &quot;Dakota&quot;, &quot;Samuel&quot;, &quot;Nikita&quot;,\n                            &quot;Koani&quot;, &quot;Saya&quot;, &quot;Yiska&quot;, &quot;Yumaevsky&quot; };\n      foreach (var arrName in arrNames)\n         names.Add(arrName);\n   }\n   \n   private static List&lt;String&gt; GetData() \n   {\n      return null;   \n   \n   }\n}\n// The example displays output like the following:\n//    Unhandled Exception: System.NullReferenceException: Object reference \n//    not set to an instance of an object.\n//       at Example.PopulateNames(List`1 names)\n//       at Example.Main()\n</code></pre><p> To address this issue, make sure that the argument passed to the method is not <code>null</code>, or handle the thrown exception in a <code>try…catch…finally</code> block. For more information, see <a href=\"../Topic/Handling%20and%20Throwing%20Exceptions.md\" data-linktype=\"relative-path\">Exceptions</a>.  </p>\n<p>The following Microsoft intermediate language (MSIL) instructions throw NullReferenceException: <code>callvirt</code>, <code>cpblk</code>, <code>cpobj</code>, <code>initblk</code>, <code>ldelem.&lt;type&gt;</code>, <code>ldelema</code>, <code>ldfld</code>, <code>ldflda</code>, <code>ldind.&lt;type&gt;</code>, <code>ldlen</code>, <code>stelem.&lt;type&gt;</code>, <code>stfld</code>, <code>stind.&lt;type&gt;</code>, <code>throw</code>, and <code>unbox</code>.  </p>\n<p>NullReferenceException uses the HRESULT COR_E_NULLREFERENCE, which has the value 0x80004003.  </p>\n<p>For a list of initial property values for an instance of NullReferenceException, see the <a class=\"xref\" href=\"system.nullreferenceexception#System_NullReferenceException__ctor_\" data-linktype=\"relative-path\">NullReferenceException</a> constructors.  </p>\n<p><strong>Handling NullReferenceException in release code</strong>  </p>\n<p>It&#39;s usually better to avoid a NullReferenceException than to handle it after it occurs. Handling an exception can make your code harder to maintain and understand, and can sometimes introduce other bugs. A NullReferenceException is often a non-recoverable error. In these cases, letting the exception stop the app might be the best alternative.  </p>\n<p>However, there are many situations where handling the error can be useful:  </p>\n</li>\n<li><p>Your app can ignore objects that are null. For example, if your app retrieves and processes records in a database, you might be able to ignore some number of bad records that result in null objects. Recording the bad data in a log file or in the application UI might be all you have to do.  </p>\n</li>\n<li><p>You can recover from the exception. For example, a call to a web service that returns a reference type might return null if the connection is lost or the connection times out. You can attempt to reestablish the connection and try the call again.  </p>\n</li>\n<li><p>You can restore the state of your app to a valid state. For example, you might be performing a multi-step task that requires you to save information to a data store before you call a method that throws a NullReferenceException. If the uninitialized object would corrupt the data record, you can remove the previous data before you close the app.  </p>\n</li>\n<li><p>You want to report the exception. For example, if the error was caused by a mistake from the user of your app, you can generate a message to help him supply the correct information. You can also log information about the error to help you fix the problem. Some frameworks, like ASP.NET, have a high-level exception handler that captures all errors to that the app never crashes; in that case, logging the exception might be the only way you can know that it occurs.</p>\n</li>\n</ul>\n\r\n    \r\n    \r\n    <h2>Constructors\r\n     summary</h2>\r\n    \r\n    <table class=\"nameValue\">\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_NullReferenceException__ctor\" data-linktype=\"self-bookmark\">NullReferenceException()</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a> class, setting the <span class=\"xref\">stem.Exception.Message*</span> property of the new instance to a system-supplied message that describes the error, such as &quot;The value &#39;null&#39; was found where an instance of an object was required.&quot; This message takes into account the current system culture.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_NullReferenceException__ctor_System_String_\" data-linktype=\"self-bookmark\">NullReferenceException(String)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a> class with a specified error message.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_NullReferenceException__ctor_System_Runtime_Serialization_SerializationInfo_System_Runtime_Serialization_StreamingContext_\" data-linktype=\"self-bookmark\">NullReferenceException(SerializationInfo,StreamingContext)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a> class with serialized data.</p>\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\" enable-platform-filter\">\r\n          <td>\r\n            <div class=\"lang-csharp\"><a href=\"#System_NullReferenceException__ctor_System_String_System_Exception_\" data-linktype=\"self-bookmark\">NullReferenceException(String,Exception)</a></div>\r\n          </td>\r\n            <td>\r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n\r\n            </td>\r\n        </tr>\r\n    </table>\r\n    <section class=\"memberGroup\">\r\n      <header class=\"header enable-platform-filter\" id=\"constructors\">\r\n        <h2>Constructors\r\n    </h2>\r\n      </header>\r\n    \r\n      <ul class=\"list-clean enable-platform-filter\">\r\n    \r\n        <li class=\" enable-platform-filter\" id=\"System_NullReferenceException__ctor\">\r\n    \r\n            <a id=\"System_NullReferenceException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">NullReferenceException()</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a> class, setting the <span class=\"xref\">stem.Exception.Message*</span> property of the new instance to a system-supplied message that describes the error, such as &quot;The value &#39;null&#39; was found where an instance of an object was required.&quot; This message takes into account the current system culture.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public NullReferenceException ();</code></pre>\r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>The following table shows the initial property values for an instance of <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a>.  </p>\n<table>\n<thead>\n<tr>\n<th>Property</th>\n<th>Value</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a></td>\n<td><code>null</code>.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a></td>\n<td>The localized error message string.</td>\n</tr>\n</tbody>\n</table>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_NullReferenceException__ctor_System_String_\">\r\n    \r\n            <a id=\"System_NullReferenceException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">NullReferenceException(String)</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a> class with a specified error message.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public NullReferenceException (string message);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>message</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>A <a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a> that describes the error. The content of <code>message</code> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>The following table shows the initial property values for an instance of <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a>.  </p>\n<table>\n<thead>\n<tr>\n<th>Property</th>\n<th>Value</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a></td>\n<td><code>null</code>.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a></td>\n<td>The error message string.</td>\n</tr>\n</tbody>\n</table>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_NullReferenceException__ctor_System_Runtime_Serialization_SerializationInfo_System_Runtime_Serialization_StreamingContext_\">\r\n    \r\n            <a id=\"System_NullReferenceException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">NullReferenceException(SerializationInfo,StreamingContext)</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a> class with serialized data.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">protected NullReferenceException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>info</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.serializationinfo\" data-linktype=\"relative-path\">SerializationInfo</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The object that holds the serialized object data.</p>\n\r\n                </li>\r\n                <li>\r\n                  <dl>\r\n                  <dt>context</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.streamingcontext\" data-linktype=\"relative-path\">StreamingContext</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The contextual information about the source or destination.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see <a href=\"../Topic/XML%20and%20SOAP%20Serialization.md\" data-linktype=\"relative-path\">XML and SOAP Serialization</a>.</p>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n        <li class=\" enable-platform-filter\" id=\"System_NullReferenceException__ctor_System_String_System_Exception_\">\r\n    \r\n            <a id=\"System_NullReferenceException__ctor_\"></a>\r\n    \r\n    \r\n          <div class=\"memberName\">\r\n            <div class=\"lang-csharp\">NullReferenceException(String,Exception)</div>        \r\n          </div>\r\n    \r\n            <p>Initializes a new instance of the <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n\r\n    \r\n            <pre class=\"memberDeclaration\"><code class=\"csharp lang-csharp\">public NullReferenceException (string message, Exception innerException);</code></pre>\r\n    \r\n    \r\n              <h4>Parameters</h4>\r\n              <ul class=\"memberDetails\">\r\n                <li>\r\n                  <dl>\r\n                  <dt>message</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The error message that explains the reason for the exception.</p>\n\r\n                </li>\r\n                <li>\r\n                  <dl>\r\n                  <dt>innerException</dt>\r\n                  <dd>\r\n                    <div class=\"lang-csharp\"><a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a></div>\r\n                  </dd>\r\n                  </dl>\r\n                  <p>The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not <code>null</code>, the current exception is raised in a <code>catch</code> block that handles the inner exception.</p>\n\r\n                </li>\r\n              </ul>\r\n    \r\n    \r\n    \r\n    \r\n          \r\n    \r\n            <h4>Remarks</h4>\r\n            <p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property. The <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property returns the same value that is passed into the constructor, or <code>null</code> if the <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property does not supply the inner exception value to the constructor.  </p>\n<p> The following table shows the initial property values for an instance of <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a>.  </p>\n<table>\n<thead>\n<tr>\n<th>Property</th>\n<th>Value</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a></td>\n<td>The inner exception reference.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a></td>\n<td>The error message string.</td>\n</tr>\n</tbody>\n</table>\n\r\n    \r\n    \r\n    \r\n        </li>\r\n      </ul>\r\n    </section>\r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n","outputRootRelativePath":"./","pageMetadata":"<meta name=\"breadcrumb_path\" content=\"breadcrumb/toc.json\">\r\n<meta name=\"search.ms_sitename\" content=\"Docs\">\r\n<meta name=\"search.ms_docsetname\" content=\"fulldocset\">\r\n<meta name=\"locale\" content=\"en-us\">\r\n<meta name=\"site_name\" content=\"Docs\">\r\n<meta name=\"search.ms_product\" content=\"MSDN\">\r\n<meta name=\"depot_name\" content=\"MSDN.fulldocset\">\r\n<meta name=\"ref_skeleton_gitcommit\" content=\"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/501959ac03e19ac52a27aa4c6bbeb980f8b11c8c/fulldocset/System.NullReferenceException.yml\">\r\n<meta name=\"original_ref_skeleton_git_url\" content=\"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/System.NullReferenceException.yml\">\r\n<meta name=\"APIName\" content=\"System.NullReferenceException\">\r\n<meta name=\"APIName\" content=\"System.NullReferenceException..ctor\">\r\n<meta name=\"APILocation\" content=\"mscorlib.dll\">\r\n<meta name=\"TopicType\" content=\"apiref\">\r\n<meta name=\"APIType\" content=\"Assembly\">\r\n<meta name=\"updated_at\" content=\"2017-03-01 01:37 AM\">\r\n<meta name=\"document_id\" content=\"62db1a84-cc90-8bef-569b-bd3d7488b8ea\">\r\n<meta name=\"pagetype\" content=\"Reference\">\r\n<meta name=\"description\" content=\"The exception that is thrown when there is an attempt to dereference a null object reference.\n\">\r\n<meta name=\"toc_rel\" content=\"_splitted/System/toc.json\">\r\n<meta name=\"source_url\" content=\"\">\r\n<meta name=\"ms.assetid\" content=\"System.NullReferenceException\">\r\n","rawMetadata":{"breadcrumb_path":"breadcrumb/toc.json","search.ms_sitename":"Docs","search.ms_docsetname":"fulldocset","version":null,"_op_canonicalUrlPrefix":"https://ppe.docs.microsoft.com/en-us/fulldotnet/","locale":"en-us","site_name":"Docs","search.ms_product":"MSDN","_op_openToPublicContributors":true,"depot_name":"MSDN.fulldocset","_op_gitRefSkeletonCommitHistory":[{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"use plugin in master","commit_sha":"501959ac03e19ac52a27aa4c6bbeb980f8b11c8c","commit_date":"2017-03-01 09:31:20 +0800"},{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"switch from platform to version","commit_sha":"78cdacb5ca782478af490a6b30c3a2cb2b6b873e","commit_date":"2017-02-28 15:09:51 +0800"},{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"update platforms","commit_sha":"39ad5a8919a59afc93a79ac4bd8e07c3b471b37a","commit_date":"2017-02-28 10:38:59 +0800"},{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"checkin yml","commit_sha":"da161b792852497df7140d7768cee2eccd9cb43f","commit_date":"2017-02-28 09:36:15 +0800"}],"ref_skeleton_gitcommit":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/501959ac03e19ac52a27aa4c6bbeb980f8b11c8c/fulldocset/System.NullReferenceException.yml","original_ref_skeleton_git_url":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/System.NullReferenceException.yml","open_to_public_contributors":true,"api_name":["System.NullReferenceException","System.NullReferenceException..ctor"],"api_location":["mscorlib.dll"],"topic_type":["apiref"],"api_type":["Assembly"],"f1_keywords":["System.NullReferenceException","System::NullReferenceException","System.NullReferenceException.#ctor","System::NullReferenceException::#ctor"],"dev_langs":["csharp"],"updated_at":"2017-03-01 01:37 AM","document_id":"62db1a84-cc90-8bef-569b-bd3d7488b8ea","content_git_url":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/xml/System/NullReferenceException.xml","layout":"Reference","_op_layout":"Reference","pagetype":"Reference","title":"NullReferenceException class | Microsoft Docs","_op_ogTitle":"NullReferenceException class","description":"The exception that is thrown when there is an attempt to dereference a null object reference.\n","toc_asset_id":"_splitted/System/toc.json","toc_rel":"_splitted/System/toc.json","source_url":"","ms.assetid":"System.NullReferenceException","canonical_url":"https://ppe.docs.microsoft.com/en-us/mergedepotdynamic/system.nullreferenceexception","_op_canonicalUrl":"https://ppe.docs.microsoft.com/en-us/mergedepotdynamic/system.nullreferenceexception","fileRelativePath":"System.NullReferenceException.html"},"themesRelativePathToOutputRoot":"_themes/"}